language: ruby
cache: bundler
sudo: false
before_install: gem update
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
  - ree
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false -Xcompat.version=2.0'
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    - rvm: jruby-18mode
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  allow_failures:
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    - rvm: ruby-head
    - rvm: rbx
script: bundle exec rake spec
notifications:
  slack:
    rooms:
      - thekompanee:p46x27zMG89XW66DgGuutoaW#open-source
